import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { Complaint, User, UserRole } from '../types';

export const exportToPDF = (complaints: Complaint[], user: User) => {
  const doc = new jsPDF();

  // Document Info
  const timestamp = new Date().toLocaleString();
  const title = 'Disaster Complaint Report';
  const subtitle = `Generated by: ${user.name} (${user.role}${user.role === UserRole.OFFICER ? ` - ${user.dsd}` : ''})`;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(40);
  doc.text(title, 14, 22);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(subtitle, 14, 30);
  doc.text(`Date: ${timestamp}`, 14, 36);

  // Table Columns
  const columns = [
    { header: 'ID', dataKey: 'id' },
    { header: 'Title', dataKey: 'title' },
    { header: 'Category', dataKey: 'category' },
    { header: 'Location', dataKey: 'location' },
    { header: 'DSD', dataKey: 'dsd' },
    { header: 'Priority', dataKey: 'priority' },
    { header: 'Status', dataKey: 'status' },
    { header: 'Date', dataKey: 'date' },
  ];

  // Table Data
  const data = complaints.map(c => ({
    id: c.id,
    title: c.title,
    category: c.category,
    location: c.location,
    dsd: c.dsd,
    priority: c.priority,
    status: c.status,
    date: new Date(c.createdAt).toLocaleDateString()
  }));

  // Generate Table
  autoTable(doc, {
    head: [columns.map(col => col.header)],
    body: data.map(row => columns.map(col => row[col.dataKey as keyof typeof row])),
    startY: 45,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [245, 245, 245] },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  doc.setFontSize(8);
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 20, doc.internal.pageSize.height - 10, { align: 'right' });
  }

  // Save File
  const filename = `complaints_${user.role === UserRole.ADMIN ? 'all' : user.dsd?.toLowerCase()}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
};

export const exportToExcel = (complaints: Complaint[], user: User) => {
  // Flatten data for Excel
  const data = complaints.map(c => ({
    ID: c.id,
    Title: c.title,
    Description: c.description,
    Category: c.category,
    Location: c.location,
    Latitude: c.latitude || '',
    Longitude: c.longitude || '',
    DSD: c.dsd,
    Priority: c.priority,
    Status: c.status,
    'Created At': new Date(c.createdAt).toLocaleString(),
    'Contact Name': c.contactName || '',
    'Contact Phone': c.contactPhone || '',
    'Remarks Count': c.remarks?.length || 0
  }));

  // Create Worksheet
  const ws = XLSX.utils.json_to_sheet(data);

  // Auto-size columns (rudimentary)
  const cols = Object.keys(data[0] || {}).map(key => ({ wch: Math.max(key.length, 15) }));
  ws['!cols'] = cols;

  // Create Workbook
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Complaints');

  // Save File
  const filename = `complaints_${user.role === UserRole.ADMIN ? 'all' : user.dsd?.toLowerCase()}_${new Date().toISOString().split('T')[0]}.xlsx`;
  XLSX.writeFile(wb, filename);
};
